### ISSUE TITLE
make repository for AUDPC data 

### ISSUE THREAD

**Issue by zkamvar** [grunwaldlab/Reproducible-science-in-R#19]
The data and short analysis is located in #5 
1. add data as csv
2. add resulting word document from Rmarkdown with code hidden, but describing the process.
3. add Rproj file

This will serve as our in-class example as we laid out in #17

**Comment by zkamvar** [comment]
A thought just occurred to me: We should probably include an R script in there that they can use for their Rmd file. This way, it will be easier for them to walk through it and it doesn't matter if they copy+paste at this stage since we will be walking them through it.

**Comment by zachary-foster** [comment]
This is done [here](https://github.com/grunwaldlab/audpc_example). Probably could be tweaked though.

**Comment by zachary-foster** [comment]
Changes to make after meeting with @zkamvar:
- [x] Make like a "lab report" (eww, high school flashbacks)
- [x] Add AUDPC calculations
- [x] output to word without code

**Comment by zkamvar** [comment]
For reference here's what I did for #20 on a new branch:

https://github.com/grunwaldlab/pinfestans_example/tree/example-solution

I rendered it as a word document and moved it to the master branch.

**Comment by zachary-foster** [comment]
this is done, at least in draft form
