### ISSUE TITLE
Do something about the TOC not working right

### ISSUE THREAD

**Issue by zachary-foster** [grunwaldlab/Reproducible-science-in-R#28]
I tried to fix this in quiltr last night, but it is a complicated problem. Basically, the HTML anchors need to be opened in the iframe they are in. This is different than links to external sites, which need to open in a new window. Even if the two type are automatically differentiated (which should be possible by applying the css `target: "_self"` to "a" elements in the "TOC" div), it is uncertain wether it is possible to use HTML anchors in iframes in firefox:
- http://stackoverflow.com/questions/15646782/anchor-links-inside-iframe-does-nothing
- http://stackoverflow.com/questions/9687085/jump-link-inside-an-iframe

[This page](https://portal.airplus.com/faq.do?anchor=Security&TKN=0.gopmx4) uses anchors in an iframe; it does not work with firefox, but does work with chrome).

I can think of the following solutions:
- Fix this in quiltr, although I am not sure if this is possible to do easily.
- Remove the TOC
- Remove the links in the TOC using css if possible (maybe something like `div#TOC a {href: NULL}`)
- Make the website using something besides quiltr.  We could take the menu made by quiltr and add it to `includes:  in_header: in_header.html` to the `_output.yaml` and create a "makefile.R" to knit all the documents. Alternativly, and probably better, would be to follow [this procedure](http://rmarkdown.rstudio.com/rmarkdown_websites.html). 

Thoughts?

**Comment by zkamvar** [comment]
I think for the time being the best idea would be to remove the TOC all together since we are so close to the workshop. Later, we can refine this. 

We used a prototype of the procedure outlined in your last point for the population genetics in R website. It used to involve hand-coding the dropdown menu, but it looks like that's not necessary anymore with their `_site.yml`.

**Comment by zkamvar** [comment]
I've been thinking about this and, given the fact that quiltr is not meant to create proper websites and the fact that linking in iframes is not possible without javascript, the best option for this website in the future is to utilize the procedure outlined in the rmarkdown documents.

**Comment by zachary-foster** [comment]
I agree.
