### ISSUE TITLE
Make numbering of section titles consistent

### ISSUE THREAD

**Issue by zachary-foster** [grunwaldlab/Reproducible-science-in-R#29]
The home page and "Setup" have numbers prefixing their titles and the rest do not. Which convention do we want to follow? I don’t care much either way.

**Comment by zkamvar** [comment]
remove the numbers, it's easier to move things around that way

**Comment by zkamvar** [comment]
Again, these were copy/paste jobs by Dear Leader.

**Comment by zachary-foster** [comment]
Haha, will do.
