### ISSUE TITLE
RMarkdown section awaiting review

### ISSUE THREAD

**Issue by zachary-foster** [grunwaldlab/Reproducible-science-in-R#3]
I am done with the content of the RMarkdown section and will wait until I get feedback before working on it more. The styling can be modified using the functions in `function.R` and the css in `tutorial.css`. Feel free to make changes or respond with comments on this issue. Once everyone feels it is ready, we can close the issue. Thanks!

**Comment by grunwald** [comment]
I finished reviewing the Rmarkdown file. Looks great! Also pushed all my commits. Nice job!

**Comment by zachary-foster** [comment]
Thanks! The edits look good to me.
