### ISSUE TITLE
On quitting R

### ISSUE THREAD

**Issue by zachary-foster** [grunwaldlab/Reproducible-science-in-R#31]
I am going through the website and making some "final" edits and I have a question.

On the setup chapter there is:

```
To quit R you can either use the RStudio > Quit pull-down menu command or execute ⌘ + Q (OS X) or ctrl + Q (PC).
```

yet, before that, there is:

```
To exit R, simply close the RStudio application.
```

Do you mind if I delete the "To quit R you can..." section? Or is there some subtle difference between the two points I am missing?

**Comment by zkamvar** [comment]
You can delete that. I believe it was copypasta

**Comment by zachary-foster** [comment]
Thanks for the speedy response. Will do.

**Comment by knausb** [comment]
What's wrong with:

```
q()
```

? I miss ESS.

**Comment by zachary-foster** [comment]
Where is `q()`? I cant find it on the dropdown menu...

**Comment by zkamvar** [comment]
👏

**Comment by knausb** [comment]
😰
