### ISSUE TITLE
Make chapter for discussion on organization

### ISSUE THREAD

**Issue by zkamvar** [grunwaldlab/Reproducible-science-in-R#9]
This should include folder structure, working habits, and ensuring things are organized at the end.

**Comment by zachary-foster** [comment]
Here is a start of an outline. Feel free to add to it if you want. 

Folder structure:
- [ ] Organization philosophy is a personal choice; carefully pick something that works for you and stick to it
- [ ] Consider adding "README" files for each directory 
- [ ] Use the same structure on all your computers 
- [ ] Dont use OS-specific premade folders like "My Documents"
- [ ] Use subfolders when needed and dont worry about depth

File names:
- [ ] Use informative names; you should be able to tell what is in a file in general by looking at its path
- [ ] Avoid any character that is not a letter, number, underscore, or dash. This means no spaces.
- [ ] Avoid capitalization 
- [ ] If a file is only relevant to a specific date, then prefix it with YYYY_MM_DD
- [ ] If a file represents one step in a set of related processes, prefix it with a number like 001_, 002, etc
- [ ] Use subdirectories to avoid redundancies in long file names when possible, but not at the expense of clarity or usability.

Working habits:
- [ ] Stick to your organizational system unless you find it to be fundamentally flawed or enjoy reorganizing things; don’t slack
- [ ] Use a scratch folder when you are not sure what to do with something or are not sure if you will keep it, but don’t leave it in there for long. Organize it or delete it. 
- [ ] Use shortcuts/links to commonly accessed files

**Comment by zachary-foster** [comment]
This is done in draft form, but it probably needs more work. A few figures or examples would be good.

**Comment by zkamvar** [comment]
Thanks. I'll have a look.
